---
- name: restart linkding
  community.docker.docker_compose_v2:
    project_src: /data/services/linkding
    files:
      - compose.yml
    state: present
    recreate: always
    remove_orphans: false
