---
- name: restart paperless-ng
  community.docker.docker_compose_v2:
    project_src: /data/services/paperless-ng
    files:
      - compose.yml
    state: present
    recreate: always
    remove_orphans: false
