---
- name: restart litellm
  community.docker.docker_compose_v2:
    project_src: /data/services/litellm
    files:
      - compose.yml
    state: present
    recreate: always
    remove_orphans: false
