managed_hosts:
  children:
    raspberrypi:
    pihole:
    dns:
    edge:
    containers:
    plex_stack:
    overseer:
    bazarr:
    lidarr:
    sonarr:
    radarr:
    homepage:
    paperless-ng:
    photoprism:
    tubearchivist:
    nextcloud:
    traggo:
    freshrss:
    linkding:
    homeassistant:
    # monitoring
    prometheus:
    pihole-exporter:
    docmost:
    # additional services
    nebula-sync:
    portainer:
    teslamate:
    musicassistant:
    syncthing:
    kimai:
    navidrome:
    jellyfin:
    kavita:
    audiobookshelf:
    whisparr:
    jellyseerr:
    tdarr:
    immich:
    kasm:
    baserow:
    n8n:
    monica:
    ofelia:
    semaphore:
    ghostfolio:
    obsidian:
    cura:
    blinko:
    outline:
    mylar3:
    samba:
    diun:
    openclaw:
