- name: Create services folder
  ansible.builtin.file:
    path: /data/services/ghostfolio
    state: directory
    owner: ansible
    group: docker

- name: Setup environment file for Ghostfolio stack
  template:
    src: env.j2
    dest: /data/services/ghostfolio/.env
    owner: ansible
    group: docker

- name: Setup docker compose file for Ghostfolio stack
  template:
    src: docker-compose.j2
    dest: /data/services/ghostfolio/docker-compose.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/ghostfolio/docker-compose.yml up -d"
