---
- name: restart syncthing
  community.docker.docker_compose_v2:
    project_src: /data/services/syncthing
    files:
      - compose.yml
    state: present
    recreate: always
    remove_orphans: false
