---
- name: restart bazarr
  community.docker.docker_compose_v2:
    project_src: /data/services/bazarr
    files:
      - compose.yml
    state: present
    recreate: always
    remove_orphans: false
