---
- name: restart baserow
  community.docker.docker_compose_v2:
    project_src: /data/services/baserow
    files:
      - compose.yml
    state: present
    recreate: always
    remove_orphans: false
