---
- name: Update PiHole container with latest image
  community.docker.docker_compose_v2:
    project_src: /data/services/pihole
    files:
      - compose.yml
    state: present
    pull: always
    recreate: always
    remove_orphans: false

- name: Wait for PiHole container to be running
  community.docker.docker_container_info:
    name: pihole
  register: pihole_status
  until: pihole_status.container.State.Running | default(false)
  retries: 5
  delay: 2

- name: Display update status
  debug:
    msg: "PiHole has been updated and is running"

- name: Remove dangling PiHole images
  command: docker image prune -f
  changed_when: true
