---
- name: restart searxng
  community.docker.docker_compose_v2:
    project_src: /data/services/searxng
    files:
      - compose.yml
    state: present
    recreate: always
    remove_orphans: false
