---
- name: restart mylar3
  community.docker.docker_compose_v2:
    project_src: /data/services/mylar3
    files:
      - compose.yml
    state: present
    recreate: always
    remove_orphans: false
