---
# Setup tasks for Nextcloud AIO environment file creation
# Run via: ansible-playbook site-setup.yml

- name: Create nextcloud config directory locally
  file:
    path: "{{ playbook_dir }}/../homelab_config/ansible/files/config/nextcloud"
    state: directory
    mode: '0755'
  delegate_to: 127.0.0.1
  become: false

- name: Check if environment file already exists
  stat:
    path: "{{ playbook_dir }}/../homelab_config/ansible/files/config/nextcloud/environment"
  register: nextcloud_env_file
  delegate_to: 127.0.0.1
  become: false

- name: Create environment file from template
  template:
    src: ../templates/environment.j2
    dest: "{{ playbook_dir }}/../homelab_config/ansible/files/config/nextcloud/environment"
    mode: '0640'
  when: not nextcloud_env_file.stat.exists
  delegate_to: 127.0.0.1
  become: false

- name: Display setup instructions
  debug:
    msg: |
      Nextcloud AIO environment file created at: {{ playbook_dir }}/../homelab_config/ansible/files/config/nextcloud/environment

      Please review and update the following settings:
      - TZ: Timezone for the service
      - APACHE_PORT: Internal Apache port (default 11000)
      - NEXTCLOUD_DATADIR: Path to Nextcloud data directory

      After configuration, deploy with: ansible-playbook site.yml --limit nextcloud
  when: not nextcloud_env_file.stat.exists
  delegate_to: 127.0.0.1
  become: false
