# This is used to manage Ansible role dependences
# # http://docs.ansible.com/galaxy.html#installing-multiple-roles-from-a-file
# # Install with: `ansible-galaxy install -r requirements.yml`
#

#- name: oh-my-zsh 
#  src: gantsign.oh-my-zsh 

collections:
  - name: kewlfft.aur
  - name: tribe29.checkmk
  - name: ansible.posix
    version: ">=1.5.0"  # Updated version to avoid deprecation warnings
  - name: community.general
    version: ">=7.0.0"  # Required for sudoers module