---
- name: restart cloudflare-ddns
  community.docker.docker_compose_v2:
    project_src: /data/services/cloudflare-ddns
    files:
      - compose.yml
    state: restarted
    remove_orphans: false
