---
- name: restart paperless-ngx
  community.docker.docker_compose_v2:
    project_src: /data/services/paperless-ngx
    files:
      - compose.yml
    state: present
    recreate: always
    remove_orphans: false
