---
- name: restart sonarr
  community.docker.docker_compose_v2:
    project_src: /data/services/sonarr
    files:
      - compose.yml
    state: present
    recreate: always
    remove_orphans: false
