---
- hosts: 'proxmox_control_node_by_ip'
  remote_user: root
  tasks:
    - name: apt update
      include_tasks: roles/common/tasks/apt-update.yml

#- hosts: "workstations"
#  tasks:
#    - name: apt update
#      include_tasks: roles/common/tasks/apt-update.yml

- hosts: 'pihole'
  remote_user: ansible
  tasks:
    - name: "Update PiHole"
      include_tasks: roles/pihole/tasks/update.yml

- hosts: 'pihole-exporter'
  remote_user: ansible
  tasks:
    - name: "Update PiHole Exporter"
      include_tasks: roles/pihole-exporter/tasks/update.yml

- hosts: "prometheus"
  remote_user: ansible
  tasks:
    - name: "Update Prometheus"
      include_tasks: roles/prometheus/tasks/update.yml

- hosts: "nebula-sync"
  remote_user: ansible
  tasks:
    - name: "Update Nebula Sync"
      include_tasks: roles/nebula-sync/tasks/update.yml

- hosts: "n8n"
  remote_user: ansible
  tasks:
    - name: "Update N8N"
      include_tasks: roles/n8n/tasks/update.yml

- hosts: "monica"
  remote_user: ansible
  tasks:
    - name: "Update Monica"
      include_tasks: roles/monica/tasks/update.yml
      when: groups['monica'] is defined and groups['monica'] | length > 0

- hosts: "containers"
  remote_user: ansible
  tasks:
    - name: "Update Traefik"
      include_tasks: roles/traefik/tasks/update.yml
    - name: "Update Portainer"
      include_tasks: roles/portainer/tasks/update.yml

- hosts: "diun"
  remote_user: ansible
  tasks:
    - name: "Update Diun"
      include_tasks: roles/diun/tasks/update.yml

- hosts: "syncthing"
  remote_user: ansible
  tasks:
    - name: "Update Syncthing"
      include_tasks: roles/syncthing/tasks/update.yml
      when: groups['syncthing'] is defined and groups['syncthing'] | length > 0

- hosts: "edge"
  remote_user: ansible
  tasks:
    - name: "Update Traefik"
      include_tasks: roles/traefik/tasks/update.yml
    - name: "Update Cloudflare DDNS"
      include_tasks: roles/cloudflare-ddns/tasks/update.yml
    - name: "Update WireGuard Easy"
      include_tasks: roles/wg-easy/tasks/update.yml
    - name: "Update Authelia"
      include_tasks: roles/authelia/tasks/update.yml
      tags:
        - authelia
        - edge

- hosts: "portainer"
  remote_user: ansible
  tasks:
    - name: "Update Portainer"
      include_tasks: roles/portainer/tasks/update.yml

- hosts: "jellyfin"
  remote_user: ansible
  tasks:
    - name: "Update Jellyfin"
      include_tasks: roles/jellyfin/tasks/update.yml

- hosts: "kavita"
  remote_user: ansible
  tasks:
    - name: "Update Kavita"
      include_tasks: roles/kavita/tasks/update.yml
      when: groups['kavita'] is defined and groups['kavita'] | length > 0

- hosts: "navidrome"
  remote_user: ansible
  tasks:
    - name: "Update Navidrome"
      include_tasks: roles/navidrome/tasks/update.yml

- hosts: "freshrss"
  remote_user: ansible
  tasks:
    - name: "Update FreshRSS"
      include_tasks: roles/freshrss/tasks/update.yml

- hosts: "audiobookshelf"
  remote_user: ansible
  tasks:
    - name: "Update Audiobookshelf"
      include_tasks: roles/audiobookshelf/tasks/update.yml

- hosts: "tubearchivist"
  remote_user: ansible
  tasks:
    - name: "Update TubeArchivist"
      include_tasks: roles/tubearchivist/tasks/update.yml

- hosts: "blinko"
  remote_user: ansible
  tasks:
    - name: "Update Blinko"
      include_tasks: roles/blinko/tasks/update.yml

- hosts: "baserow"
  remote_user: ansible
  tasks:
    - name: "Update Baserow"
      include_tasks: roles/baserow/tasks/update.yml

- hosts: "outline"
  remote_user: ansible
  tasks:
    - name: "Update Outline"
      include_tasks: roles/outline/tasks/update.yml

- hosts: "kimai"
  remote_user: ansible
  tasks:
    - name: "Update Kimai"
      include_tasks: roles/kimai/tasks/update.yml
      when: groups['kimai'] is defined and groups['kimai'] | length > 0

- hosts: "semaphore"
  remote_user: ansible
  tasks:
    - name: "Update Semaphore"
      include_tasks: roles/semaphore/tasks/update.yml
      when: groups['semaphore'] is defined and groups['semaphore'] | length > 0

- hosts: "sabnzbd"
  remote_user: ansible
  tasks:
    - name: "Update Sabnzbd"
      include_tasks: roles/sabnzbd/tasks/update.yml
      tags:
        - sabnzbd
        - arrs

- hosts: "transmission-openvpn"
  remote_user: ansible
  tasks:
    - name: "Update Transmission-OpenVPN"
      include_tasks: roles/transmission-openvpn/tasks/update.yml
      tags:
        - transmission
        - transmission-openvpn
        - arrs

- hosts: "mylar3"
  remote_user: ansible
  tasks:
    - name: "Update Mylar3"
      include_tasks: roles/mylar3/tasks/update.yml
      tags:
        - mylar3
        - arrs

- hosts: "whisparr"
  remote_user: ansible
  tasks:
    - name: "Update Whisparr"
      include_tasks: roles/whisparr/tasks/update.yml
      tags:
        - whisparr

- hosts: "prowlarr"
  remote_user: ansible
  tasks:
    - name: "Update Prowlarr"
      include_tasks: roles/prowlarr/tasks/update.yml
      tags:
        - prowlarr
        - arrs

- hosts: "flaresolverr"
  remote_user: ansible
  tasks:
    - name: "Update Flaresolverr"
      include_tasks: roles/flaresolverr/tasks/update.yml
      tags:
        - flaresolverr
        - arrs

- hosts: "bazarr"
  remote_user: ansible
  tasks:
    - name: "Update Bazarr"
      include_tasks: roles/bazarr/tasks/update.yml
      tags:
        - bazarr
        - arrs

- hosts: "lidarr"
  remote_user: ansible
  tasks:
    - name: "Update Lidarr"
      include_tasks: roles/lidarr/tasks/update.yml
      tags:
        - lidarr
        - arrs

- hosts: "sonarr"
  remote_user: ansible
  tasks:
    - name: "Update Sonarr"
      include_tasks: roles/sonarr/tasks/update.yml
      tags:
        - sonarr
        - arrs

- hosts: "radarr"
  remote_user: ansible
  tasks:
    - name: "Update Radarr"
      include_tasks: roles/radarr/tasks/update.yml
      tags:
        - radarr
        - arrs

- hosts: "bentopdf"
  remote_user: ansible
  tasks:
    - name: "Update BentoPDF"
      include_tasks: roles/bentopdf/tasks/update.yml
      tags:
        - bentopdf

- hosts: "tdarr"
  remote_user: ansible
  tasks:
    - name: "Update Tdarr"
      include_tasks: roles/tdarr/tasks/update.yml
      tags:
        - tdarr

#- hosts: 'managed_hosts'
#  remote_user: ansible
#  tasks:
#    - name: "Update BorgBackup"
 #     include_tasks: roles/borgbackup/tasks/update.yml

#- hosts: 'containers:watchtower:dns:edge'
#  remote_user: ansible
#  tasks:
#    - name: "Update containers"
#      include_tasks: roles/watchtower/tasks/update.yml

