- name: Create services folder
  ansible.builtin.file:
    path: /data/services/paperless-ng
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for paperless-ng
  template:
    src: docker-compose.j2
    dest: /data/services/paperless-ng/docker-compose.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/paperless-ng/docker-compose.yml up -d"
