- name: Create services folder
  ansible.builtin.file:
    path: /data/services/traggo
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for Traggo stack
  template:
    src: docker-compose.j2
    dest: /data/services/traggo/docker-compose.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/traggo/docker-compose.yml up -d"
