- name: Create services folder (docmost)
  become: true
  ansible.builtin.file:
    path: /data/services/docmost
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file (docmost)
  template:
    src: docker-compose.j2
    dest: /data/services/docmost/compose.yml
    owner: ansible
    group: docker

- name: Copy environment configuration
  copy:
    src: "{{ playbook_dir }}/../homelab_config/ansible/files/config/docmost/environment"
    dest: /data/services/docmost/.env
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/docmost/compose.yml up -d"
